import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthSessionProvider } from "./providers/session-provider";
import { getSession } from "@/lib/auth";
import { ThemeProvider } from "./providers/theme-provider";
import { Navbar, SkipToContent } from "./components/ui/navigation";

const geistSans = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Get the session from the server
  const session = await getSession();

  return (
    <html lang="en" data-theme="bumblebee">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthSessionProvider session={session}>
          <ThemeProvider>
            <SkipToContent />
            <Navbar />
            <main id="main-content">
              {children}
            </main>
          </ThemeProvider>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
